# Generated by Django 5.1.5 on 2025-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinBot', '0003_auto_20201012_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
